SELECT ID FROM
(SELECT ID, TEMPERATURE, LAG(TEMPERATURE, 1) OVER (ORDER BY RECORDDATE) AS PREV_TEMP, DATEDIFF(DAY, LAG(RECORDDATE, 1) OVER (ORDER BY RECORDDATE), RECORDDATE) AS DAY_DIFF
FROM WEATHER) TEMP 
WHERE TEMPERATURE > PREV_TEMP AND DAY_DIFF = 1